name: Check formatting using prettier and yapf
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          npm install
          pip install -r requirements.txt
      - name: Run formatting check
        run: npm run check-format
