name: Validate templates on Push and PR

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          npm install
      - name: Run Prettier check
        run: npx prettier --check "."
      - name: Run validation script
        working-directory: templates
        run: python validate.py
